module.exports = [
  {
    name: 'Monstera Deliciosa',
    slug: 'monstera-deliciosa',
    shortDesc: 'Hojas perforadas icónicas',
    description: 'Planta tropical de interior con hojas grandes y perforadas. Ideal para luz media y ambientes húmedos.',
    price: 52000,
    compareAtPrice: 60000,
  images: [ { url: 'https://source.unsplash.com/800x600/?monstera,plant' } ],
    categories: ['Interior','Tropical'],
    badges: ['nuevo','top'],
    care: { light: 'media', watering: 'medio', temp: '18–26°C' },
    size: 'L',
    dimensions: '60–90 cm',
    potRecommended: '25 cm diámetro',
    stock: 12,
    ratingAvg: 4.8,
    ratingCount: 37,
    salesCount: 120,
    isFeatured: true
  },
  {
    name: 'Ficus Lyrata',
    slug: 'ficus-lyrata',
    shortDesc: 'Conocida como "Higuera de hoja de violín"',
    description: 'Sus hojas grandes en forma de violín aportan elegancia a cualquier espacio luminoso indirecto.',
    price: 68000,
    compareAtPrice: 75000,
  images: [ { url: 'https://source.unsplash.com/800x600/?ficus,plant' } ],
    categories: ['Interior','Árbol'],
    badges: ['top'],
    care: { light: 'alta', watering: 'medio', temp: '20–28°C' },
    size: 'L',
    dimensions: '80–110 cm',
    potRecommended: '30 cm diámetro',
    stock: 8,
    ratingAvg: 4.6,
    ratingCount: 22,
    salesCount: 90,
    isFeatured: true
  },
  {
    name: 'Sansevieria Trifasciata',
    slug: 'sansevieria-trifasciata',
    shortDesc: 'Lengua de suegra resistente',
    description: 'Planta extremadamente resistente que tolera baja luz y riegos espaciados. Purifica el aire.',
    price: 32000,
    compareAtPrice: 38000,
  images: [ { url: 'https://source.unsplash.com/800x600/?sansevieria,plant' } ],
    categories: ['Interior','Suculentas'],
    badges: ['facil'],
    care: { light: 'baja', watering: 'poco', temp: '15–30°C' },
    size: 'M',
    dimensions: '35–50 cm',
    potRecommended: '18 cm diámetro',
    stock: 25,
    ratingAvg: 4.9,
    ratingCount: 58,
    salesCount: 200,
    isFeatured: false
  },
  {
    name: 'Pilea Peperomioides',
    slug: 'pilea-peperomioides',
    shortDesc: 'Planta del dinero china',
    description: 'Hojas redondas y verdes sobre tallos delgados. Crecimiento rápido con luz brillante filtrada.',
    price: 28000,
  images: [ { url: 'https://source.unsplash.com/800x600/?pilea,plant' } ],
    categories: ['Interior'],
    badges: ['nuevo'],
    care: { light: 'media', watering: 'medio', temp: '16–24°C' },
    size: 'S',
    dimensions: '20–30 cm',
    potRecommended: '14 cm diámetro',
    stock: 30,
    ratingAvg: 4.5,
    ratingCount: 11,
    salesCount: 35,
    isFeatured: false
  },
  {
    name: 'Calathea Orbifolia',
    slug: 'calathea-orbifolia',
    shortDesc: 'Follaje con bandas plateadas',
    description: 'Requiere humedad y luz indirecta. Sus hojas anchas con franjas plateadas son muy decorativas.',
    price: 45000,
  images: [ { url: 'https://source.unsplash.com/800x600/?calathea,plant' } ],
    categories: ['Interior','Tropical'],
    badges: ['exotica'],
    care: { light: 'media', watering: 'frecuente', temp: '18–26°C' },
    size: 'M',
    dimensions: '40–55 cm',
    potRecommended: '20 cm diámetro',
    stock: 14,
    ratingAvg: 4.2,
    ratingCount: 19,
    salesCount: 60,
    isFeatured: false
  },
  {
    name: 'Succulent Mix',
    slug: 'succulent-mix',
    shortDesc: 'Colección de suculentas variadas',
    description: 'Pack de 4 suculentas seleccionadas que requieren muy poco riego y buena luz.',
    price: 25000,
  images: [ { url: 'https://source.unsplash.com/800x600/?succulent,succulents' } ],
    categories: ['Interior','Suculentas'],
    badges: ['pack'],
    care: { light: 'alta', watering: 'poco', temp: '18–30°C' },
    size: 'S',
    dimensions: '10–15 cm',
    potRecommended: 'Macetas pequeñas 8-10 cm',
    stock: 40,
    ratingAvg: 4.7,
    ratingCount: 33,
    salesCount: 150,
    isFeatured: false
  },
  {
    name: 'Aloe Vera',
    slug: 'aloe-vera',
    shortDesc: 'Gel medicinal natural',
    description: 'Suculenta famosa por su gel. Requiere luz brillante y riegos moderados.',
    price: 21000,
  images: [ { url: 'https://source.unsplash.com/800x600/?aloe,vera' } ],
    categories: ['Interior','Suculentas','Medicinal'],
    badges: ['medicinal'],
    care: { light: 'alta', watering: 'poco', temp: '18–32°C' },
    size: 'M',
    dimensions: '30–45 cm',
    potRecommended: '16 cm diámetro',
    stock: 34,
    ratingAvg: 4.6,
    ratingCount: 29,
    salesCount: 110,
    isFeatured: false
  },
  {
    name: 'Cactus Echinopsis',
    slug: 'cactus-echinopsis',
    shortDesc: 'Flores espectaculares nocturnas',
    description: 'Cactus que produce grandes flores nocturnas. Muy fácil de cuidar con luz directa.',
    price: 19000,
  images: [ { url: 'https://source.unsplash.com/800x600/?cactus,echinopsis' } ],
    categories: ['Interior','Suculentas','Cactus'],
    badges: ['flor'],
    care: { light: 'alta', watering: 'poco', temp: '15–30°C' },
    size: 'S',
    dimensions: '12–18 cm',
    potRecommended: '12 cm diámetro',
    stock: 28,
    ratingAvg: 4.4,
    ratingCount: 17,
    salesCount: 55,
    isFeatured: false
  },
  {
    name: 'Helecho Boston',
    slug: 'helecho-boston',
    shortDesc: 'Follaje frondoso y colgante',
    description: 'Necesita humedad y riegos frecuentes. Perfecto para colgar en espacios luminosos indirectos.',
    price: 26000,
  images: [ { url: 'https://source.unsplash.com/800x600/?fern,plant' } ],
    categories: ['Interior','Tropical'],
    badges: ['colgante'],
    care: { light: 'media', watering: 'frecuente', temp: '16–24°C' },
    size: 'M',
    dimensions: '35–50 cm',
    potRecommended: '18 cm diámetro',
    stock: 21,
    ratingAvg: 4.3,
    ratingCount: 13,
    salesCount: 47,
    isFeatured: false
  },
  {
    name: 'Dracaena Marginata',
    slug: 'dracaena-marginata',
    shortDesc: 'Tronco estilizado y hojas finas',
    description: 'Planta de interior muy adaptable. Tolera luz media y riegos moderados.',
    price: 39000,
  images: [ { url: 'https://source.unsplash.com/800x600/?dracaena,plant' } ],
    categories: ['Interior','Árbol'],
    badges: ['clasica'],
    care: { light: 'media', watering: 'medio', temp: '18–26°C' },
    size: 'L',
    dimensions: '70–95 cm',
    potRecommended: '24 cm diámetro',
    stock: 16,
    ratingAvg: 4.5,
    ratingCount: 25,
    salesCount: 75,
    isFeatured: false
  }
];
